version: "3.8"
services:
  nextjs:
    container_name: nextjs-dev
    build: .
    volumes:
      - .:/app
      - /node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: npm run dev
